---
#  etcd
ansible_user: dbadmin
etcd_data_dir: "/var/lib/etcd"
etcd_conf_file: "/etc/etcd/etcd.conf"
etcd_cluster_name: "etcd-postgres-cluster"

##postgres

postgresql_version: "11"
postgrespro_minor_version: "{{ postgresql_version }}.11.1"

postgresql_data_dir: "/var/lib/pgpro/std-{{ postgresql_version }}/data"
postgresql_conf_dir: "{{ postgresql_data_dir }}"
postgresql_bin_dir: "/opt/pgpro/std-{{ postgresql_version }}/bin"
postgresql_unix_socket_dir: "/tmp"

postgresql_packages:
  - gcc
  - python3-module-psycopg2
  - python3-dev
  - python3-module-pip
  - python3-module-setuptools
  - postgrespro-std-11-server
  - postgrespro-std-11-client
  - postgrespro-std-11-libs
  - postgrespro-std-11-contrib
  - pgpro-pgbadger

apt_repository_keys:
  - key: "https://repo.postgrespro.ru/keys/GPG-KEY-POSTGRESPRO"

apt_repository:
  - "rpm http://ftp.altlinux.org/pub/distributions/ALTLinux c9f1/branch/x86_64 classic"
  - "rpm http://ftp.altlinux.org/pub/distributions/ALTLinux c9f1/branch/noarch classic"
  - "rpm http://repo.postgrespro.ru/std-11/altlinux-spt/8.2 x86_64 pgpro"
  - "rpm http://repo.postgrespro.ru/std-11/altlinux-spt/8.2 noarch pgpro"





