---
- name: Wait until the etcd cluster is healthy
  command: >
     /usr/bin/etcdctl endpoint health --endpoints=http://localhost:2379
  register: etcd_health_result
  until: "'is healthy' in etcd_health_result.stdout"
  retries: 3
  delay: 1
  changed_when: false
  ignore_errors: false

- debug:
    msg: "{{ etcd_health_result.stdout }}"
   tags: etcd, etcd_start, etcd_status
