---
- name: Enable and start etcd service
  systemd:
    daemon_reload: true
    name: etcd
    enabled: true
    state: started
  tags: etcd, etcd_start

- name: Wait for port 2379 to become open on the host
  wait_for:
    port: 2379
    host: 127.0.0.1
    state: started
    timeout: 120
    delay: 10
  ignore_errors: false
  tags: etcd, etcd_start
