---
- name: Create user with adm
  user:
    name: "{{ create_user }}"
    password: "{{ user_password }}"
    groups: wheel
    shell: "/bin/bash"
    create_home: true
    state: present
  register: users

- debug:
    var: users

- name: Set authorized key for remote user
  ansible.posix.authorized_key:
    user: "{{ create_user }}"
    state: present
    key: "{{ copy_local_key }}"
