---
 - name: Install PostgresPro
   become: yes
   become_method: sudo
   gather_facts: yes
   any_errors_fatal: true
   hosts: PGSQL_SERVERS
   vars_files:
    - vars/deploy.yml
    - vars/main.yml

   roles:
     - deploy_postgres_cluster
